image: node:8.12.0
pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@11.2.9
  - npm install
  - ng build
  - mv dist/ngx-translate-app/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages